### ISSUE TITLE
No package shadowsocks-libev available

### ISSUE THREAD

**Issue by EricBigGod** [librehat/shadowsocks-libev#10]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
This is a installation problem.

### What operating system are you using?
centerOS7

### What did you do?
step1: yum install epel-release -y
step2: yum install gcc gettext autoconf libtool automake make pcre-devel asciidoc xmlto c-ares-devel libev-devel libsodium-devel mbedtls-devel -y
step3: su -c 'yum update'
step4: su -c 'yum install shadowsocks-libev'

[root@host ~]# yum install shadowsocks-libev
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: repos.lax.quadranet.com
 * elrepo-kernel: elrepo.org
 * extras: centos.mirror.ndchost.com
 * updates: mirrors.usc.edu
No package shadowsocks-libev available.
Error: Nothing to do

### What did you see instead?
I cann't find shadowsocks-libev in yum.

**Comment by theLastOfCats** [comment]
It might be stupid question, but do you add [this repo](https://copr.fedorainfracloud.org/coprs/librehat/shadowsocks/repo/epel-7/librehat-shadowsocks-epel-7.repo)?

**Comment by sixg0000d** [comment]
`yum install yum-copr-plugin`
`yum copr enable librehat/shadowsocks`
`yum update`
`yum install shadowsocks-libev`
