### ISSUE TITLE
Fedora 29 - linking error to libmbedcrypto.so.2

### ISSUE THREAD

**Issue by vladimir-lu** [librehat/shadowsocks-libev#11]
After installing the package from copr on Fedora 29, the `ss-local` binary cannot be run, due to a linking error to `libmbedcrypto.so.2`. I think the package simply needs to be rebuilt. 

Btw downloading files from https://file.librehat.com does not work at the moment, they all give 403 errors which sounds like a small config problem.

**Comment by librehat** [comment]
Hmm, I think because Fedora has moved the version numbers of the libraries.. I'll submit a rebuild

**Comment by librehat** [comment]
`sudo dnf update --refresh` should solve your issue now. I've also fixed the nginx configuration on my server. Thanks
