### ISSUE TITLE
Unable to find a match: shadowsocks-libev

### ISSUE THREAD

**Issue by qifei** [librehat/shadowsocks-libev#15]
CentOS 8 x64

[root@vultrguest ~]# dnf install shadowsocks-libev
Last metadata expiration check: 0:07:04 ago on Tue 14 Apr 2020 09:46:27 AM UTC.
No match for argument: shadowsocks-libev
Error: Unable to find a match: shadowsocks-libev

[root@vultrguest ~]# yum install shadowsocks-libev
Last metadata expiration check: 0:07:40 ago on Tue 14 Apr 2020 09:46:27 AM UTC.
No match for argument: shadowsocks-libev
Error: Unable to find a match: shadowsocks-libev

**Comment by qifei** [comment]
[root@vultrguest ~]# dnf copr enable librehat/shadowsocks

You are about to enable a Copr repository. Please note that this
repository is not part of the main distribution, and quality may vary.

The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr>,
and packages are not held to any quality or security level.

Please do not file bug reports about these packages in Fedora
Bugzilla. In case of problems, contact the owner of this repository.

Do you really want to enable copr.fedorainfracloud.org/librehat/shadowsocks? [y/N]: y
Error: This repository does not have any builds yet so you cannot enable it now.

**Comment by librehat** [comment]
I am not maintaining the COPR for shadowsocks anymore
