### ISSUE TITLE
Upgrade shadowsocks-libev to 3.1.0

### ISSUE THREAD

**Issue by unlimitedsola** [librehat/shadowsocks-libev#3]

**Comment by XVilka** [comment]
There is a security problem even in the 3.1.0 version:

X41 D-Sec GmbH Security Advisory: X41-2017-010

Command Execution in Shadowsocks-libev
======================================

Overview
--------
Severity Rating: High
Confirmed Affected Versions: 3.1.0
Confirmed Patched Versions: N/A
Vendor: Shadowsocks
Vendor URL: https://github.com/shadowsocks/shadowsocks-libev
Vector: Local
Credit: X41 D-Sec GmbH, Niklas Abel
Status: Public
CVE: not yet assigned
Advisory-URL:
https://www.x41-dsec.de/lab/advisories/x41-2017-010-shadowsocks-libev/

See more at https://bugs.gentoo.org/634422

**Comment by unlimitedsola** [comment]
@XVilka I don't think this really matter.

**Comment by XVilka** [comment]
Yes, because this repo seems totally dead.

**Comment by XVilka** [comment]
Now shadowsocks released 3.1.1 version already https://github.com/shadowsocks/shadowsocks-libev/commit/82198aece8cfbbb07fb536452dd73a9261665fd2

**Comment by unlimitedsola** [comment]
@XVilka ,I saw that @librehat upgraded to 3.1.0 few days ago, lol

**Comment by librehat** [comment]
I'll update it to 3.1.1 when I have some time

**Comment by guxin0123** [comment]
[2017-10-14 Vendor patched the vulnerability](https://github.com/shadowsocks/shadowsocks-libev/issues/1734)

**Comment by yswtrue** [comment]
hope upgrade to 3.1.3 `Fix a bug in UDP relay.` thx

**Comment by librehat** [comment]
3.1.3 rpm is there for RHEL 6.x, 7.x, Fedora 26 and Fedora 27: 
https://copr.fedorainfracloud.org/coprs/librehat/shadowsocks/build/724124/

Due to newer GCC in fedora 28 and rawhide, this version is not available there
