### ISSUE TITLE
Add systemd unit file for Fedora/CentOS/etc

### ISSUE THREAD

**Issue by XVilka** [librehat/shadowsocks-libev#4]
See https://gist.github.com/guyskk/a9665bc6b2a89b73fae34678b1f6dc6b

**Comment by unlimitedsola** [comment]
https://github.com/shadowsocks/shadowsocks-libev/commit/feeaff85e156e09f1636ed3a47ac9375c81ceb87
already in 3.1.0

**Comment by librehat** [comment]
This will be done by upgrading to 3.1.0
