### ISSUE TITLE
Is there a better way to avoid SS error after yum update?

### ISSUE THREAD

**Issue by HarrisonXi** [librehat/shadowsocks-libev#5]
### What version of shadowsocks-libev are you using?

I installed the latest version from https://copr.fedorainfracloud.org/coprs/librehat/shadowsocks/ via yum.

### What operating system are you using?

CentOS 7

### What did you do?

yum update -y

### What did you expect to see?

SS can run as usual.

### What did you see instead?

ss-server: error while loading shared libraries: libmbedcrypto.so.0: cannot open shared object file: No such file or directory

### Reason

mbedtls was upgraded to 2.7.0 and only contains libmbedcrypto.so.1
I have to find a way to downgrade mbedtls to 2.6.0
Or download libmbedcrypto.so.0 manually

### Question

Is there a better way to avoid SS error after yum update?

**Comment by HarrisonXi** [comment]
find a way to fix it, just copy the libmbedcrypto.so.1 to libmbedcrypto.so.0:

```
➜  ~ ss-server -c /etc/shadowsocks-libev/config.json
ss-server: error while loading shared libraries: libmbedcrypto.so.0: cannot open shared object file: No such file or directory
➜  ~ find / -name 'libmbedcrypto.so.*'
/usr/lib64/libmbedcrypto.so.1
/usr/lib64/libmbedcrypto.so.2.7.0
➜  ~ cp /usr/lib64/libmbedcrypto.so.1 /usr/lib64/libmbedcrypto.so.0
➜  ~ ss-server -c /etc/shadowsocks-libev/config.json               
 2018-03-08 09:52:19 INFO: initializing ciphers... aes-256-gcm
 2018-03-08 09:52:19 INFO: tcp server listening at xx.xx.xx.xx:xxxx
 2018-03-08 09:52:19 INFO: running from root user
```

**Comment by librehat** [comment]
It was explained in #6
