### ISSUE TITLE
ss-libev 3.1.3 in yum was built against a different libmbedtls

### ISSUE THREAD

**Issue by CovMat** [librehat/shadowsocks-libev#6]
Dear maintainer:

I found in EPEL for CentOS 7 x64, ```shadowsocks-libev-3.1.3-1.el7.centos.x86_64``` was built against a different ```libmbedtls```. ```mbedtls-devel-2.7.0-1.el7.x86_64``` dont have ```libmbedcrypto.so.0```.

I report this problem in : https://github.com/shadowsocks/shadowsocks-libev/issues/1966

Could you read the above issue and check where is the problem?

Many thanks

**Comment by PeterCxy** [comment]
Confirmed again on CentOS 7 with latest epel updates. The `mbedtls` was upgraded, therefore shadowsocks should also be rebuilt

**Comment by diocat** [comment]
use a symlink "libmbedcrypto.so.0" to create link to the origin file. 

or use this bad solution
cp /usr/lib64/libmbedcrypto.so.1 /usr/lib64/libmbedcrypto.so.0

**Comment by amavlyanov** [comment]
The same issue here. Please, rebuild with right naming on centos 7
`[root@ams2-centos7-console shadowsocks-libev]# ss-server --help
ss-server: error while loading shared libraries: libmbedcrypto.so.0: cannot open shared object file: No such file or directory
`

the right name for libmbedcrypto library on centos 7 is:
`/usr/lib64/libmbedcrypto.so.1`


p.s. the solution above is working, but it's not a fix, just a workaround

**Comment by librehat** [comment]
Will trigger a rebuild now

**Comment by librehat** [comment]
Do an upgrade after https://copr.fedorainfracloud.org/coprs/librehat/shadowsocks/build/758340/ finishes
