### ISSUE TITLE
no package avialable

### ISSUE THREAD

**Issue by 1026359484n** [librehat/shadowsocks-libev#7]
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
lasted

### What operating system are you using?
centos7

### What did you do?
install

### What did you expect to see?
success

### What did you see instead?
no package available

**Comment by WangFive** [comment]
```
wget  -P /home/download/ https://copr.fedorainfracloud.org/coprs/librehat/shadowsocks/repo/epel-7/librehat-shadowsocks-epel-7.repo
```

**Comment by theLastOfCats** [comment]
Same for me, after update on Fedora 28.

Console output:
`No match for argument: shadowsocks-libev
Error: Unable to find a match
`

Repolist:
```dnf repolist
Last metadata expiration check: 0:06:15 ago on Th 03 may 2018 10:39:27.
repo id                     repo name                                     status
*fedora                     Fedora 28 - x86_64                            57 317
librehat-shadowsocks        Copr repo for shadowsocks owned by librehat       11
*rpmfusion-free             RPM Fusion for Fedora 28 - Free                  559
*rpmfusion-free-updates     RPM Fusion for Fedora 28 - Free - Updates         16
*rpmfusion-nonfree          RPM Fusion for Fedora 28 - Nonfree               203
*rpmfusion-nonfree-updates  RPM Fusion for Fedora 28 - Nonfree - Updates       5
*updates                    Fedora 28 - x86_64 - Updates                   2 096
```

**Comment by librehat** [comment]
@theLastOfCats Fedora 28 uses separate rpms. CentOS 7 should be supported, make sure you have the copr enabled
