### ISSUE TITLE
Requires: libsodium >= 1.0.4 \n Installed: libsodium-0.4.5-3.el6.x86_64

### ISSUE THREAD

**Issue by chiboreache** [librehat/shadowsocks-libev#8]
CentOS 6 x64 - something definitely goes wrong

![screenshot_20180429_214709](https://user-images.githubusercontent.com/16459251/39409372-85b2888e-4bee-11e8-8aff-4ab7fa45b604.png)

`Resolving Dependencies
--> Running transaction check
---> Package shadowsocks-libev.x86_64 0:3.1.3-1.el7.centos will be installed
--> Processing Dependency: libsodium >= 1.0.4 for package: shadowsocks-libev-3.1.3-1.el7.centos.x86_64
--> Processing Dependency: systemd for package: shadowsocks-libev-3.1.3-1.el7.centos.x86_64
--> Processing Dependency: systemd for package: shadowsocks-libev-3.1.3-1.el7.centos.x86_64
--> Finished Dependency Resolution
Error: Package: shadowsocks-libev-3.1.3-1.el7.centos.x86_64 (librehat-shadowsocks)
Requires: systemd
Error: Package: shadowsocks-libev-3.1.3-1.el7.centos.x86_64 (librehat-shadowsocks)
Requires: libsodium >= 1.0.4
Installed: libsodium-0.4.5-3.el6.x86_64 (@epel)
libsodium = 0.4.5-3.el6
You could try using --skip-broken to work around the problem
You could try running: rpm -Va --nofiles --nodigest`

**Comment by yexingok** [comment]
@chombor if you on Centos7, you can solve the libsodium>= 1.0.4 issue by install the [remi repo](https://rpms.remirepo.net/)

From the error message, it seems the latest 3.1.3 version requires systemd, which does not support Centos6 anymore.., it would be good to keep all the old packages in the repo though fyi: @librehat

**Comment by librehat** [comment]
You're trying to install the rpm from centos 7... Please stick to the binary rpm that was intended for CentOS 6
