### ISSUE TITLE
Pls support fedora 28

### ISSUE THREAD

**Issue by daoleno** [librehat/shadowsocks-libev#9]
### What version of shadowsocks-libev are you using?
Not yet.
I want to use shadowsocks-libev on fedora 28.

### What operating system are you using?
fedora 28
```
Linux 4.16.5-300.fc28.x86_64 x86_64 GNU/Linux
```

### What did you do?
I enable fedora repo.
I find shadowsocks-libev build failed on fedora 28
https://copr.fedorainfracloud.org/coprs/librehat/shadowsocks/monitor/

### What did you expect to see?
Can you support fedora 28?
Thanks a lot.

### What did you see instead?
When I exec dnf search shadowsocks-libev, there is nothing.

### What is your config in detail (with all sensitive info masked)?
None.

**Comment by whitewolf712** [comment]
I just replaced in shadowsocks-libev.spec
`%configure --enable-shared`

by
```
%if 0%{?fedora} >= 28
%configure CC="gcc -w" --enable-shared 
%else
%configure --enable-shared
%endif
```

and the rpm successfully builded.

Solution based on this issue - https://github.com/shadowsocks/shadowsocks-libev/issues/2036.

I do not know how to make and send patches. Sorry.

**Comment by librehat** [comment]
I don't think that's a good solution, the warning should be fixed instead.

**Comment by librehat** [comment]
I will try to fix the errors myself over the weekend if I get time

**Comment by librehat** [comment]
The issue has been fixed in the upstream, I will pack the RPMs once a new version is released

**Comment by librehat** [comment]
Long resolved
